### ISSUE TITLE
1.1.2 NPE's in console

### ISSUE THREAD

**Issue by Gingied** [WiIIiam278/HuskClaims#99] opened 2024-04-23 01:00 UTC
```
[19:00:10 WARN]: [HuskClaims] Plugin HuskClaims v1.1.2 generated an exception while executing task 1515949
java.lang.NullPointerException: null
[19:00:10 WARN]: [HuskClaims] Plugin HuskClaims v1.1.2 generated an exception while executing task 1515948
java.lang.NullPointerException: null
[19:00:10 WARN]: [HuskClaims] Plugin HuskClaims v1.1.2 generated an exception while executing task 1515947
java.lang.NullPointerException: null
```
Seeing these in console occasionally, seems to be related to this:
```
[19:30:17 WARN]: [HuskClaims] Plugin HuskClaims v1.1.2 generated an exception while executing task 12990
java.lang.NullPointerException: Cannot invoke "String.length()" because "str" is null
        at java.io.DataOutputStream.writeUTF(DataOutputStream.java:359) ~[?:?]
        at java.io.DataOutputStream.writeUTF(DataOutputStream.java:333) ~[?:?]
        at com.google.common.io.ByteStreams$ByteArrayDataOutputStream.writeUTF(ByteStreams.java:643) ~[guava-32.1.2-jre.jar:?]
        at net.william278.huskclaims.network.PluginMessageBroker.send(PluginMessageBroker.java:84) ~[HuskClaims-1.1.2.jar:?]
        at net.william278.huskclaims.network.Message.send(Message.java:75) ~[HuskClaims-1.1.2.jar:?]
        at net.william278.huskclaims.user.UserManager.lambda$editSavedUser$1(UserManager.java:80) ~[HuskClaims-1.1.2.jar:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at net.william278.huskclaims.user.UserManager.lambda$editSavedUser$2(UserManager.java:75) ~[HuskClaims-1.1.2.jar:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at net.william278.huskclaims.user.UserManager.editSavedUser(UserManager.java:75) ~[HuskClaims-1.1.2.jar:?]
        at net.william278.huskclaims.user.UserManager.editSavedUser(UserManager.java:66) ~[HuskClaims-1.1.2.jar:?]
        at net.william278.huskclaims.user.UserManager.editUserPreferences(UserManager.java:86) ~[HuskClaims-1.1.2.jar:?]
        at net.william278.huskclaims.claim.ClaimWorld.lambda$isIgnoringClaims$18(ClaimWorld.java:220) ~[HuskClaims-1.1.2.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.4.jar:git-Purpur-2174]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.20.4.jar:git-Purpur-2174]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.20.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

Purpur 1.20.4
Velocity 3.3.0

**Comment by WiIIiam278** [comment] 2024-04-23 01:12
Duplicate of #92 (already fixed)

**Closed by WiIIiam278** 2024-04-23 01:12 UTC
