### ISSUE TITLE
Claim flags - Wilderness not working

### ISSUE THREAD

**Issue by Gingied** [WiIIiam278/HuskClaims#93] opened 2024-04-21 03:53 UTC
Velocity 3.3.0
Purpur 1.20.4
World is named "creative" - I'm trying to configure the creative server to have different flags compared to my other survival servers in the network (e.g. restricting building to claims). After removing many of the default flags from the wilderness section of the config, there appears to be no change in build permission, or any other permissions as far as I can tell. 
I'm using worldedit/worldguard and the "creative" world is the primary world for this server if that matters. There is no multiverse or multi-world plugin installed.

**Comment by WiIIiam278** [comment] 2024-04-21 09:47
Duplicate of #94

**Closed** 2024-04-21 09:47 UTC
